name: Codecov
on: [push]
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Generate coverage report
        run: |
          yarn install
          yarn coverage
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }} # not required for public repos
          directory: ./coverage/
          files: ./clover.xml # optional
          fail_ci_if_error: true # optional (default = false)
          verbose: true # optional (default = false)
